Test cases for `processors/ayon_hiero_effect_file.py`
ynput/LabLib pull request #43
Opened 2024-12-12 08:01 UTC by jakubjezek001

Adding more coverage for `ayon_hiero_effect_file.py` file.

2024-12-16 09:20 UTC, tweak-wtf requested changes

2024-12-16 09:20 UTC, tweak-wtf commented on tests/test_processors_ayon_hiero_effect_file.py
> +            Path("dummy.json")
seems this `dummy.json` isn't available in the repo.
https://github.com/ynput/LabLib/actions/runs/12292170415/job/34302276633#step:9:272

let's push this into `resources/public`

2025-02-24 10:52 UTC, jakubjezek001 commented on tests/test_processors_ayon_hiero_effect_file.py
> +            Path("dummy.json")
ah, yeah. It seems like it is actually missing even on my machine. Will look into the code again and see if it is actually needed anymore.

2025-02-24 16:20 UTC, tweak-wtf commented on tests/test_processors_ayon_hiero_effect_file.py
> +            Path("dummy.json")
alrighty. thanks for checking this out 🙏

2025-04-02 14:03 UTC, tweak-wtf reviewed
perfecto :)

2025-04-02 14:03 UTC, merged